# Generated by Django 4.2.1 on 2023-05-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=48)),
                ('password', models.CharField(max_length=128)),
                ('uri', models.CharField(max_length=128)),
                ('notes', models.TextField()),
            ],
        ),
    ]
